compute_environment: LOCAL_MACHINE
deepspeed_config: main/ds_config.json
distributed_type: MULTI_GPU
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 3
same_network: true