compute_environment: LOCAL_MACHINE
deepspeed_config: {
  "zero_optimization": {
    "stage": 2,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    "contiguous_gradients": true,
    "overlap_comm": true
  },
  "bf16": {
    "enabled": true
  },
  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": 2e-5,
      "betas": [0.9, 0.999],
      "eps": 1e-8,
      "weight_decay": 0.01
    }
  },
  "gradient_clipping": 1.0,
  "gradient_accumulation_steps": 4,
  "train_micro_batch_size_per_gpu": 1
}
distributed_type: DEEPSPEED
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 3
same_network: true